
- name: Deploy select application
- hosts: appservers
  vars: 
   environment_name: cpp_migration
   install_dir: c:\koukia_build\
   goals: install ALL
   log_file: build
  tasks:
   -name: Create install dir
    raw: mkdir {{install_dir}}\{{environment_name}}
    register: c_dir
   - debug: var=c_dir