
- name: Deploy select application
  hosts: windows
  gather_facts: False
  vars: 
     environment_name: cpp_migration
     install_dir: c:\koukia_build\
     goals: install ALL
     log_file: build
  tasks:
  - name: Create install dir
    raw: mkdir {{install_dir}}\{{environment_name}}
    ignore_errors: yes
    register: c_dir
    
