
- name: Deploy select application
  hosts: windows
  gather_facts: False

  vars: 
     environment_name: cpp_migration
     install_dir: c:\koukia_build\
     goals: install ALL
     log_file: build

  tasks:

  - name: Create install dir
    raw: mkdir {{install_dir}}\{{environment_name}}
    ignore_errors: yes
 
  - name: Check installjaddon exist   
    win_stat: path={{install_dir}}\{{environment_name}}\sonarqube-5.1.1.zip
    register: file_info
    
  - name: Download InstallJaddon
    raw: wget  http://downloads.sonarsource.com/sonarqube/sonarqube-5.1.1.zip -P {{install_dir}}\{{environment_name}}
    when: file_info.stat.exists == false
